### ISSUE TITLE
Segfault when running numpy

### ISSUE THREAD

**Issue by LaurentMazare** [zshipko/ocaml-py#9]
I get some non-deterministic segfault when running the line below:
```ocaml
    let np = PyModule.import "numpy" in
```
Strangely this seems to only happen when using some specific conda environment. When using the system installed numpy library this seems to always work fine.
This also seems to work fine in this conda environment with pyml so I suspect it could be related to either some environment setup/initialization (e.g. python path/home/prefix), or to the way external libraries are linked.
Anyway I'll try digging deeper into it when I get a chance, I'm just posting this here in case anyone has already run into this.

The stacktrace is in [gdb.txt](https://github.com/zshipko/ocaml-py/files/2799048/gdb.txt). Here are some highlights (note that I just used `py_test.ml` to run the single line above and turned off the rest of numpy testing).

```
Starting program: /home/laurent/github/ocaml-py/_build/default/test/py_test.exe 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: Corrupted shared library list: 0x5555559af430 != 0x7ffff7ffd9f0

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6a34b20 in PyLong_Type () from /home/laurent/miniconda3/envs/pytorch/lib/libpython3.7m.so
#0  0x00007ffff6a34b20 in PyLong_Type () from /home/laurent/miniconda3/envs/pytorch/lib/libpython3.7m.so
...
#46 0x00007ffff6c4b9b3 in numpy_pydatetime_import () from /home/laurent/miniconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/multiarray.cpython-37m-x86_64-linux-gnu.so
#47 0x00007ffff6cee95d in PyInit_multiarray () from /home/laurent/miniconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/multiarray.cpython-37m-x86_64-linux-gnu.so
#48 0x00007ffff681460c in _PyImport_LoadDynamicModuleWithSpec () from /home/laurent/miniconda3/envs/pytorch/lib/libpython3.7m.so
#49 0x00007ffff6814b29 in _imp_create_dynamic () from /home/laurent/miniconda3/envs/pytorch/lib/libpython3.7m.so
...
#246 0x00007ffff67f8b5e in PyObject_CallFunction () from /home/laurent/miniconda3/envs/pytorch/lib/libpython3.7m.so
#247 0x00007ffff680d098 in PyImport_Import () from /home/laurent/miniconda3/envs/pytorch/lib/libpython3.7m.so
#248 0x00007ffff7bd2dae in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#249 0x00007ffff7bd271f in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#250 0x00005555556740e1 in ctypes_call (fnname=<optimised out>, function=<optimised out>, callspec_=<optimised out>, argwriter=<optimised out>, rvreader=<optimised out>)
    at /home/laurent/.opam/default/.opam-switch/build/ctypes.0.14.0/src/ctypes-foreign-base/ffi_call_stubs.c:404
#251 0x00005555556163f0 in camlCtypes_ffi__fun_502545 () at src/ctypes-foreign-base/ctypes_ffi.ml:111
#252 0x0000555555610f94 in camlPy__import_2803 () at src/py.ml:481
#253 0x0000555555609d15 in camlPy_test__py_test_numpy_1582 () at test/py_test.ml:91
#254 0x0000555555639d81 in camlStdlib__list__iter_1151 () at list.ml:106
#255 0x0000555555609f6c in camlPy_test__entry () at test/py_test.ml:110
#256 0x0000555555606349 in caml_program ()
#257 0x000055555569e83c in caml_start_program ()
#258 0x0000555555681ca5 in caml_startup_common (argv=0x7fffffffdde8, pooling=<optimised out>, pooling@entry=0) at startup.c:157
#259 0x0000555555681d0b in caml_startup_exn (argv=<optimised out>) at startup.c:162
#260 caml_startup (argv=<optimised out>) at startup.c:167
#261 0x0000555555605d5c in main (argc=<optimised out>, argv=<optimised out>) at main.c:44
quit
```

**Comment by zshipko** [comment]
Interesting, importing numpy has caused some errors in the past but I haven’t seen a segmentation fault yet! I will keep an eye on this for now.
